crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

crud/first_app/urls.py
from django.urls import path
from .views import index, studet_form, StudentInfo, StudentUpdate, StudentDelete

app_name = 'first_app'

urlpatterns = [
    path('', index, name='index'),
    path('student_form', studet_form, name='student_form'),
    path('student_info/<int:student_id>/', StudentInfo, name='student_info'),
    path('student_update/<int:student_id>', StudentUpdate, name='student_update'),
    path('student_delete/<int:student_id>', StudentDelete, name='student_delete'),
    ]

crud/first_app/models.py
from . import models
from django.db import models

class Student (models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()

    def __str__(self):
        return str(self.pk)+" "+ self.first_name + " " +self.last_name

crud/first_app/views.py
from django.shortcuts import render
from .form import StudentForm
from .models import Student

def index(request):
    student_list = Student.objects.order_by('first_name')
    diction = {'title': "index", 'student_list': student_list}
    return render(request, 'first_app/index.html', context=diction)


def studet_form(request):
    form = StudentForm()
    if request.method == "POST":
        form = StudentForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': 'student_form', 'student_form':form}
    return render(request, 'first_app/student_form.html', context=diction)



def StudentInfo(request, student_id):
    student_info = Student.objects.get(pk=student_id)
    diction = {'student_info':student_info}
    return render(request, 'first_app/student_info.html', context=diction)


def StudentUpdate(request, student_id):
    student_info = Student.objects.get(pk=student_id)
    form = StudentForm(instance=student_info)

    if request.method == "POST":
        form = StudentForm(request.POST, instance=student_info)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'student_form':form}
    return render(request, 'first_app/student_update.html', context=diction)



def StudentDelete(request, student_id):
    student_dlt = Student.objects.get(pk=student_id).delete()
    diction = {'delete_message' : "Delete Done"}
    return render(request, 'first_app/student_delete.html', context = diction)

crud/templates/first_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{{ title }}</title>
</head>
<body>
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Index</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'first_app:student_form' %}">Student Form</a>
  </li>

</ul>
    {% block body_block %}

    {% endblock %}


</body>
</html>

crud/templates/first_app/index.html
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1> Student List </h1>



{% if student_list %}
{% for student in student_list %}
<ul>


<li> <a href=" {% url 'first_app:student_info' student_id=student.id %} "> {{student.first_name}}  {{student.last_name}}  </li> </a>  



{% endfor %}


{% else %}
<h1>No student</h1>


{% endif %}

</ul>
{% endblock %}

crud/templates/first_app/student_delete.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="alert alert-danger">{{ delete_message }}</div>
<h1>Delete</h1>


{% endblock %}

crud/templates/first_app/student_form.html
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1> Student Form </h1>
<form action="" method="POST">
    {{ student_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="Add Student">
</form>
{% endblock body_block %}

crud/templates/first_app/student_info.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h1>Student Info ID: {{student_info.id}}</h1>
<h2>Student Name: {{student_info.first_name}} {{student_info.last_name}}</h2>
<h3>Email: {{student_info.email}}</h3>
<h3>Phone: {{student_info.phone}}</h3>


<a href="{% url 'first_app:student_update' student_id=student_info.id %}" class="btn btn-primary">update</a>
<a href="{% url 'first_app:student_delete' student_id=student_info.id %}" class="btn btn-primary">Delete</a>


{% endblock %}

crud/templates/first_app/student_update.html
{% extends 'first_app/base.html' %}
{% block body_block %}


<h1>Student Update</h1>

<form action="" method="POST">
    {{ student_form.as_p}}
    {% csrf_token %}
</form>

<input type="submit" value="update">
{% endblock %}